import "server-only";

import { sumMoney, type Money } from "@/lib/money";
import { isSpendableAccountType } from "@/lib/accounts/spendable";
import { listAccounts } from "@/services/AccountService";
import { listRecurringTransactions } from "@/services/RecurringTransactionService";
import { listTransactions } from "@/services/TransactionService";

export interface SnapshotLine {
  id: string;
  name: string;
  amount: Money;
  currencyCode: string;
  status: "pending" | "posted";
}

export interface OneOffLine {
  id: string;
  payee: string | null;
  amount: Money;
  currencyCode: string;
  kind: "income" | "expense" | "transfer";
  transferAccountId: string | null;
  status: "pending" | "posted";
  /**
   * Only meaningful for kind: "transfer" (always false otherwise). True
   * when the transfer's destination account is NOT itself a spendable
   * cash account (checking/savings/cash) — i.e. it's paying down a
   * credit card or loan. That kind of transfer really does reduce how
   * much spendable cash you have this cycle, even though it doesn't
   * touch net worth (see NetWorthService's comment on why a card
   * payment nets to zero for net worth specifically — this is a
   * different, cash-flow question, not a net-worth one). A transfer
   * between two of your own spendable accounts is false here: your
   * total spendable cash hasn't changed, just which account it's in.
   */
  transferReducesCashOnHand: boolean;
}

export interface MonthlyBudgetSnapshot {
  /** "2026-08" */
  month: string;
  income: SnapshotLine[];
  fixedExpenses: SnapshotLine[];
  /** Card payments and other one-off items tagged to this month —
   * anything not generated from a recurring template. */
  oneOff: OneOffLine[];
  incomeTotal: Money;
  fixedExpenseTotal: Money;
}

/**
 * v0.5.0 rewrite: recurring templates are reference data now, not an
 * auto-projection. A template contributes to a month's snapshot only if
 * a real transaction has been explicitly tagged to that month
 * (cycle_month) and linked to that template (recurring_transaction_id) —
 * whether created by hand, via the Recurring page's "tag to cycle"
 * action, or auto-generated by generateDueTransactions (which tags to
 * its own occurrence month by default). Untagged templates simply don't
 * appear here at all; they're still visible and manageable on
 * /recurring, just not counted anywhere until tagged.
 *
 * This replaced the earlier occursInMonth projection entirely — there is
 * no more "projected, not yet actual" line. Everything shown is a real,
 * tagged transaction; `status` (pending vs posted) is what distinguishes
 * "committed but not yet paid" from "already happened," not a
 * projection-vs-reality distinction anymore.
 */
export async function getMonthlyBudgetSnapshot(
  month: string,
): Promise<MonthlyBudgetSnapshot> {
  const [templates, accounts, { transactions: tagged }] = await Promise.all([
    listRecurringTransactions(),
    // includeArchived: true — a transfer tagged to a past cycle can
    // point at an account that's since been archived; excluding
    // archived accounts here would make accountType.get(...) return
    // undefined for that historical transfer and silently stop
    // counting it as reducing cash-on-hand.
    listAccounts(true),
    listTransactions({ cycleMonth: month, limit: 300 }),
  ]);

  const templateName = new Map(templates.map((t) => [t.id, t.payee]));
  const accountType = new Map(accounts.map((a) => [a.id, a.accountType]));

  const live = tagged.filter((t) => t.status !== "void");

  const income: SnapshotLine[] = [];
  const fixedExpenses: SnapshotLine[] = [];
  const oneOff: OneOffLine[] = [];

  for (const transaction of live) {
    if (transaction.recurringTransactionId && transaction.kind !== "transfer") {
      const line: SnapshotLine = {
        id: transaction.id,
        name:
          transaction.payee ??
          templateName.get(transaction.recurringTransactionId) ??
          "Untitled",
        amount: transaction.amount,
        currencyCode: transaction.currencyCode,
        status: transaction.status === "posted" ? "posted" : "pending",
      };
      (transaction.kind === "income" ? income : fixedExpenses).push(line);
    } else {
      const destinationType = transaction.transferAccountId
        ? accountType.get(transaction.transferAccountId)
        : undefined;
      oneOff.push({
        id: transaction.id,
        payee: transaction.payee,
        amount: transaction.amount,
        currencyCode: transaction.currencyCode,
        kind: transaction.kind as "income" | "expense" | "transfer",
        transferAccountId: transaction.transferAccountId,
        status: transaction.status === "posted" ? "posted" : "pending",
        transferReducesCashOnHand:
          transaction.kind === "transfer" &&
          destinationType !== undefined &&
          !isSpendableAccountType(destinationType),
      });
    }
  }

  const incomeTotal = sumMoney(income.map((line) => line.amount));
  const fixedExpenseTotal = sumMoney(fixedExpenses.map((line) => line.amount));

  return {
    month,
    income,
    fixedExpenses,
    oneOff,
    incomeTotal,
    fixedExpenseTotal,
  };
}
